# Generated by Django 2.0.2 on 2018-06-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curiculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curiculum',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_course', to='courses.Course'),
        ),
    ]
