# Generated by Django 2.0.2 on 2018-06-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curiculum', '0002_auto_20180624_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curiculum',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curiculum', to='courses.Course'),
        ),
    ]
