# Generated by Django 2.0.2 on 2018-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_time_payment', '0002_onetimepayment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepayment',
            name='is_recuring',
            field=models.BooleanField(default=False),
        ),
    ]
