# Generated by Django 2.0.2 on 2018-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180626_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
