# Generated by Django 2.0.2 on 2018-07-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180705_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_enrolled',
        ),
    ]
