# Generated by Django 2.0.2 on 2018-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='is_allow_comment',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_downloadable',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_free_preview',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_pubished',
            field=models.SmallIntegerField(),
        ),
    ]
