# Generated by Django 2.0.2 on 2018-06-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20180626_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
