# Generated by Django 2.0.2 on 2018-06-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_lecture_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='quiz',
            new_name='quizzes',
        ),
    ]
