# Generated by Django 2.0.2 on 2018-07-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_remove_lecture_quizzes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='section',
            new_name='section_id',
        ),
    ]
