# Generated by Django 2.0.2 on 2018-06-24 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curiculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_created_by', to=settings.AUTH_USER_MODEL)),
                ('curiculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_id', to='curiculum.Curiculum')),
                ('updated_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'section',
            },
        ),
    ]
