# Generated by Django 2.0.2 on 2018-06-24 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20180624_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
