# Generated by Django 2.0.2 on 2018-06-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20180624_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='curiculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curiculum.Curiculum'),
        ),
    ]
