# Generated by Django 2.0.2 on 2018-06-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plan', to='course.Course'),
        ),
    ]
