# Generated by Django 2.0.2 on 2018-06-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0002_auto_20180627_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='course_id',
            new_name='course',
        ),
    ]
