# Generated by Django 2.0.2 on 2018-06-27 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0003_auto_20180627_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pricing_plan_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
