# Generated by Django 2.0.2 on 2018-06-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0004_auto_20180627_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='updated_by',
        ),
    ]
