# Generated by Django 2.0.2 on 2018-06-27 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_course_is_enrolled'),
        ('pricing_plan', '0005_auto_20180627_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plan', to='course.Course'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pricing_plan_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pricing_plan_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
