# Generated by Django 2.0.2 on 2018-06-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0006_auto_20180627_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
