# Generated by Django 2.0.2 on 2018-06-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0007_pricingplan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='price',
        ),
    ]
