<<<<<<< HEAD
# Generated by Django 2.0.2 on 2018-07-03 06:48
=======
# Generated by Django 2.0.2 on 2018-06-29 23:52
>>>>>>> 1e0c1a69fe7236aa63e70888b7d34d8a1e11b636

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0009_remove_pricingplan_is_recuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_recuring',
            field=models.BooleanField(default=False),
        ),
    ]
