# Generated by Django 2.0.2 on 2018-06-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180627_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lecture.Lecture'),
        ),
    ]
