# Generated by Django 2.0.2 on 2018-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180627_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lecture',
        ),
    ]
