# Generated by Django 2.0.2 on 2018-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
