# Generated by Django 2.0.2 on 2018-06-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180627_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_by',
        ),
    ]
