# Generated by Django 2.0.2 on 2018-06-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180627_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lecture',
        ),
    ]
