# Generated by Django 2.0.2 on 2018-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20180628_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
