# Generated by Django 2.0.2 on 2018-06-25 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_price', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
