# Generated by Django 2.0.2 on 2018-06-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0001_initial'),
        ('transaction', '0003_auto_20180627_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='course_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing_plan.PricingPlan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
