# Generated by Django 2.0.2 on 2018-06-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20180627_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pricing_plan',
        ),
    ]
