# Generated by Django 2.0.2 on 2018-06-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plan', '0004_auto_20180627_2100'),
        ('transaction', '0005_remove_transaction_pricing_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing_plan.PricingPlan'),
        ),
    ]
