# Generated by Django 2.0.2 on 2018-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_transaction_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='course_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
