# Generated by Django 2.0.2 on 2018-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
