# Generated by Django 2.0.2 on 2018-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payment', '0002_subscriptionpayment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='is_recuring',
            field=models.BooleanField(default=True),
        ),
    ]
