# Generated by Django 2.0.2 on 2018-06-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20180627_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_question', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_quiz', to='quiz.Quiz'),
        ),
    ]
