# Generated by Django 2.0.2 on 2018-06-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_auto_20180628_1330'),
        ('answer', '0004_auto_20180628_0829'),
    ]

    operations = [
    ]
