# Generated by Django 2.0.2 on 2018-07-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_auto_20180703_0648'),
        ('answer', '0006_auto_20180629_2352'),
    ]

    operations = [
    ]
