# Generated by Django 2.0.2 on 2018-06-25 19:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=12, max_digits=12)),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('end_time', models.DateField()),
            ],
            options={
                'db_table': 'SubscriptionPayment',
            },
        ),
    ]
