# Generated by Django 2.0.2 on 2018-06-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionPayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriptionpayment',
            table='subscription_payment',
        ),
    ]
