# Generated by Django 2.0.2 on 2018-06-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20180626_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='course.Course'),
        ),
    ]
