# Generated by Django 2.0.2 on 2018-07-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20180703_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='name',
        ),
    ]
